#pylint: disable=invalid-envvar-default
import configparser
import os


class Config:
    config = configparser.ConfigParser()
    config.read('src/config/config.ini')

    # CW_AUTH_SERVICE = config['CW_AUTH_SERVICE']['BaseURL']
    # CW_AUTH_SERVICE_IP = config['CW_AUTH_SERVICE']['IP']
    # CW_AUTH_SERVICE_PORT = config['CW_AUTH_SERVICE']['PORT']

    CW_LOG_TRACE = config['CW_LOG_TRACE']['BaseURL']
    CW_LOG_TRACE_IP = config['CW_LOG_TRACE']['IP']
    CW_LOG_TRACE_PORT = config['CW_LOG_TRACE']['PORT']

    CW_CENTRAL_SERVICE = config['CW_CENTRAL_SERVICE']['SERVICE']
    CW_CENTRAL_SERVICE_IP = config['CW_CENTRAL_SERVICE']['IP']
    CW_CENTRAL_SERVICE_PORT = config['CW_CENTRAL_SERVICE']['PORT']
    CW_CENTRAL_SERVICE_URL = config['CW_CENTRAL_SERVICE']['BaseURL']

    CW_MESSAGE_SERVICE_IP = config['CW_MESSAGE_SERVICE']['IP']
    CW_MESSAGE_SERVICE_PORT = config['CW_MESSAGE_SERVICE']['PORT']
    CW_MESSAGE_SERVICE_URL = config['CW_MESSAGE_SERVICE']['BaseURL']

    CW_CENTRAL_DB = config['CW_CENTRAL_DB']['URL']
    CW_CENTRAL_DB_USER = config['CW_CENTRAL_DB']['USER']
    CW_CENTRAL_DB_PASS = config['CW_CENTRAL_DB']['PASS']
    CW_CENTRAL_DB_HOST = config['CW_CENTRAL_DB']['HOST']
    CW_CENTRAL_DB_PORT = int(config['CW_CENTRAL_DB']['PORT'])
    CW_CENTRAL_DB_NAME = config['CW_CENTRAL_DB']['NAME']
    # # From Dockerfile

    # CW_AUTH_SERVICE = os.getenv('CW_AUTH_SERVICE', CW_AUTH_SERVICE)
    # CW_AUTH_SERVICE_IP = os.getenv('CW_AUTH_SERVICE_IP', CW_AUTH_SERVICE_IP)
    # CW_AUTH_SERVICE_PORT = os.getenv('CW_AUTH_SERVICE_PORT', CW_AUTH_SERVICE_PORT)

    CW_LOG_TRACE = os.getenv('CW_LOG_TRACE', CW_LOG_TRACE)
    CW_LOG_TRACE_IP = os.getenv('CW_LOG_TRACE_IP', CW_LOG_TRACE_IP)
    CW_LOG_TRACE_PORT = int(os.getenv('CW_LOG_TRACE_PORT', CW_LOG_TRACE_PORT))

    CW_CENTRAL_SERVICE = os.getenv('CW_CENTRAL_SERVICE', CW_CENTRAL_SERVICE)
    CW_CENTRAL_SERVICE_IP = os.getenv('CW_AUTH_SERVICE', CW_CENTRAL_SERVICE_IP)
    CW_CENTRAL_SERVICE_PORT = int(os.getenv('CW_CENTRAL_SERVICE_PORT', CW_CENTRAL_SERVICE_PORT))
    CW_CENTRAL_SERVICE_URL = os.getenv('CW_CENTRAL_SERVICE_URL', CW_CENTRAL_SERVICE_URL)

    CW_MESSAGE_SERVICE_IP = os.getenv('CW_MESSAGE_SERVICE_IP', CW_MESSAGE_SERVICE_IP)
    CW_MESSAGE_SERVICE_PORT = int(os.getenv('CW_MESSAGE_SERVICE_PORT', CW_MESSAGE_SERVICE_PORT))
    CW_MESSAGE_SERVICE_URL = os.getenv('CW_MESSAGE_SERVICE_URL', CW_MESSAGE_SERVICE_URL)

    CW_CENTRAL_DB = os.getenv('CW_CENTRAL_DB', CW_CENTRAL_DB)
    CW_CENTRAL_DB_USER = os.getenv('CW_CENTRAL_DB_USER', CW_CENTRAL_DB_USER)
    CW_CENTRAL_DB_PASS = os.getenv('CW_CENTRAL_DB_PASS', CW_CENTRAL_DB_PASS)
    CW_CENTRAL_DB_HOST = os.getenv('CW_CENTRAL_DB_HOST', CW_CENTRAL_DB_HOST)
    CW_CENTRAL_DB_PORT = int(os.getenv('CW_CENTRAL_DB_PORT', CW_CENTRAL_DB_PORT))
    CW_CENTRAL_DB_NAME = os.getenv('CW_CENTRAL_DB_NAME', CW_CENTRAL_DB_NAME)
