openapi: 3.0.0
info:
  title: cw-central-service
  description: CardinalWave Central Service - Serviço responsável por receber as requisições vindas do cw-mqtt-broker, e realizar as chamadas e tratametos necessarios para os demais serviços

  version: 1.1.0
servers:
  - url: http://172.168.12.1:5001
paths:
  /user/login:
    post:
      summary: Endpoint para realizar login de usuário
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  description: ID da sessão
                device:
                  type: string
                  description: Nome do dispositivo
                email:
                  type: string
                  description: E-mail do usuário
                password:
                  type: string
                  description: Senha do usuário
      responses:
        '200':
          description: Login realizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    description: E-mail do usuário
                  token:
                    type: string
                    description: Token de autenticação
                  username:
                    type: string
                    description: Nome de usuário (opcional)
                    
        '400':
          description: Requisição inválida
        '401':
          description: Credenciais inválidas
  /user/logout:
    post:
      summary: Endpoint para realizar logout de usuário
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: Token de autenticação
                username:
                  type: string
                  description: Nome de usuário
                email:
                  type: string
                  description: E-mail do usuário
      responses:
        '200':
          description: Logout realizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  payload:
                    type: string
                    enum:
                      - success
                      - error
                    description: Indica o resultado do logout
        '400':
          description: Requisição inválida
        '401':
          description: Não autorizado
  /user/register:
    post:
      summary: Endpoint para registrar um novo usuário
      tags:
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: E-mail do usuário
                username:
                  type: string
                  description: Nome de usuário
                password:
                  type: string
                  description: Senha do usuário
      responses:
        '200':
          description: Registro de usuário realizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  payload:
                    type: string
                    enum:
                      - success
                      - error
                    description: Indica o resultado do registro
        '400':
          description: Requisição inválida
        '409':
          description: Conflito - Usuário já registrado
  
  /group/join:
    post:
      summary: Endpoint para adicionar usuário a um grupo
      tags:
        - groups
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: Token de autenticação
                username:
                  type: string
                  description: Nome de usuário
                group_title:
                  type: string
                  description: Título do grupo
                group_id:
                  type: string
                  description: ID do grupo
      responses:
        '200':
          description: Usuário adicionado ao grupo com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  payload:
                    type: object
                    properties:
                      group_id:
                        type: string
                        description: ID do grupo
                      group_title:
                        type: string
                        description: Título do grupo
                      id:
                        type: string
                        description: ID do registro de associação
                      secure_email:
                        type: string
                        description: E-mail seguro
                      updated_at:
                        type: string
                        description: Data e hora da atualização
        '400':
          description: Requisição inválida
        '401':
          description: Não autorizado

  /group/create:
    post:
      summary: Endpoint para criar um novo grupo
      tags:
        - groups
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Título do grupo
      responses:
        '200':
          description: Grupo criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  payload:
                    type: object
                    properties:
                      group_id:
                        type: string
                        description: ID do grupo criado
                      title:
                        type: string
                        description: Título do grupo
        '400':
          description: Requisição inválida

  /group/list:
    post:
      summary: Endpoint para listar grupos de um usuário
      tags:
        - groups
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: Token de autenticação
                email:
                  type: string
                  description: E-mail do usuário
                username:
                  type: string
                  description: Nome de usuário
      responses:
        '200':
          description: Lista de grupos obtida com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  payload:
                    type: array
                    items:
                      type: object
                      properties:
                        group_id:
                          type: string
                          description: ID do grupo
                        title:
                          type: string
                          description: Título do grupo
        '400':
          description: Requisição inválida
        '401':
          description: Não autorizado

  /chat/join:
    post:
      summary: Endpoint para adicionar usuário a um chat de grupo
      tags:
        - chats
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: Token de autenticação
                group_id:
                  type: string
                  description: ID do grupo de chat
      responses:
        '200':
          description: Usuário adicionado ao chat de grupo com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  payload:
                    type: object
                    properties:
                      group_id:
                        type: string
                        description: ID do grupo de chat
                      group_title:
                        type: string
                        description: Título do grupo de chat
                      id:
                        type: string
                        description: ID do registro de associação
                      secure_email:
                        type: string
                        description: E-mail seguro
                      updated_at:
                        type: string
                        description: Data e hora da atualização
        '400':
          description: Requisição inválida
        '401':
          description: Não autorizado
  
  /chat/send:
    post:
      summary: Endpoint para enviar mensagem em um chat de grupo
      tags:
        - chats
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: Token de autenticação
                group_id:
                  type: string
                  description: ID do grupo de chat
                message:
                  type: string
                  description: Mensagem a ser enviada
      responses:
        '200':
          description: Mensagem enviada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  payload:
                    type: object
                    properties:
                      group_id:
                        type: string
                        description: ID do grupo de chat
                      payload:
                        type: string
                        description: Conteúdo da mensagem
                      send_time:
                        type: string
                        description: Data e hora de envio da mensagem
                      session:
                        type: object
                        properties:
                          device:
                            type: string
                            description: Dispositivo da sessão
                          session_id:
                            type: string
                            description: ID da sessão
                      username:
                        type: string
                        description: Nome de usuário que enviou a mensagem
        '400':
          description: Requisição inválida
        '401':
          description: Não autorizado